### PR TITLE
Episode 7: Add grep -r exercise

### PR DESCRIPTION
**Pull request by petersm3**
matthew@cgrb.oregonstate.edu
Instructor Training: Checkout Procedure
Part 1: Submit a Small Contribution to One of Our Lessons

Possible lesson addition for issue: Add example of "grep -r" #177

### CODE REVIEW

**Comment by petersm3** [comment]
The example may have too many files and subdirectories; it may be better to split the haiku.txt into 2 or 3 lines per file, with 6 or 4 subdirectories respectively (as opposed to 11).

**Comment by petersm3** [comment]
The setup step could be eliminated, i.e., the `mkdir`/`split`/`mv`, and the files pre-staged in [shell-novice-data.zip](http://swcarpentry.github.io/shell-novice/setup/)

**Comment by shwina** [comment]
@petersm3 

Yes, I think it would be better to pre-stage the required files/directories in the `.zip` file. It's not necessary that this example on `grep -r` use `haiku.txt` as input.

**Comment by petersm3** [comment]
Should I update this commit or create a new commit which adds the assets created by the `split` of `haiku.txt` in the `data-shell/writing` directory along with the updating of the `07-find.md` documentation, i.e., `grep -r` example, to reflect using the pre-staged files?

"It's not necessary that this example on grep -r use haiku.txt as input."

Suggestions as to how a `grep -r` example could be illustrated in the lesson? (other than using the `haiku.txt` example)

**Comment by gdevenyi** [comment]
I think us (the maintainers) need to do an audit on the content of the assets to make sure they currently match the lesson, please hold off on adding the assets until we sort that. Thanks!

**Comment by gcapes** [comment]
I'm always keen to avoid adding to the lesson unless required. Could we not have a `grep -r` exercise using the existing files in `data-shell/writing`?

**Comment by gcapes** [comment]
Something like this would show recursive grep, using the existing files in `data-shell/writing`:

```
$ grep -r Yesterday
data/LittleWomen.txt:"Yesterday, when Aunt was asleep and I was trying to be as still as a
data/LittleWomen.txt:Yesterday at dinner, when an Austrian officer stared at us and then
data/LittleWomen.txt:Yesterday was a quiet day spent in teaching, sewing, and writing in my
haiku.txt:Yesterday it worked
```

**Comment by drj11** [comment]
I would avoiding teaching `grep -r` as it is not portable. In particular, the `-r` is not required by POSIX: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/grep.html

**Comment by gcapes** [comment]
Nonetheless I just successfully tested `grep -r` on Linux, macOS and Git Bash, so it should work for all learners.

**Comment by mattipt** [comment]
A concrete example where grep -r may not work is Solaris.

**Comment by gcapes** [comment]
While that may well be true, I'm not sure this is likely to pose a problem in workshops, due to the lack of Solaris users.

**Comment by gdevenyi** [comment]
So at this point I think we'd like this rewritten to take advantage of ``data-shell/writing`` since it has the appropriate material.

**Pull request closed without merging**
