### PR TITLE
Updated CONTRIBUTING.rmd file instructions

### PR DESCRIPTION
**Pull request by wclose**
Removed excessive line breaks to make organization clearer for future modifications, made some small style revisions, clarified the instructions for how to contribute via GitHub, and fixed broken links to the repository.

### CODE REVIEW

**Comment by gdevenyi** [comment]
Hi @wclose thanks for the contribution, but I think this should go in https://github.com/swcarpentry/lesson-example/blob/gh-pages/CONTRIBUTING.md so we can pull it into this repo.

Is that correct @rgaiacs ?

**Comment by rgaiacs** [comment]
@wclose Thanks for the pull request.

> Removed excessive line breaks to make organization clearer for future modifications

Excessive line breaks is a matter of preference. I created https://github.com/swcarpentry/lesson-example/issues/134 to explain why we use "excessive line breaks". It should be better documented before but we forget. I'm happy to review our previous decision but if you want to start this discussion keep in mind that inclusion/diversity will be in first place against text editor preference.

> made some small style revisions, clarified the instructions for how to contribute via GitHub

Would be great to port the changes to https://github.com/swcarpentry/styles/blob/gh-pages/bin/lesson_initialize.py#L18. I'm very unhappy if that file but until I can [convince others](http://lists.software-carpentry.org/pipermail/maintainers/2017-October/000395.html) to change, it is the place to do the changes.

> and fixed broken links to the repository.

I imagine that the broken links are

~~~
[issues]: https://github.com/swcarpentry/FIXME/issues/
[repo]: https://github.com/swcarpentry/FIXME/
~~~

Every time that we run [bin/lesson_initialize.py](https://github.com/swcarpentry/styles/blob/gh-pages/bin/lesson_initialize.py) the links will broke. This is the reason why I want to get ride of that file but do it isn't easy. And update `CONTRIBUTING.md` from https://github.com/swcarpentry/styles/ without using [bin/lesson_initialize.py](https://github.com/swcarpentry/styles/blob/gh-pages/bin/lesson_initialize.py) is super time consuming.

**Comment by wclose** [comment]
Thanks @gdevenyi and @rgaiacs for the input and sorry for not getting back to you more quickly.  I made the changes and submitted them to  https://github.com/swcarpentry/styles/blob/gh-pages/bin/lesson_initialize.py#L18 as you requested.  I also changed the links that contained FIXME to something close that doesn't require adjustment after initialization.  The new pull request can be found at https://github.com/swcarpentry/styles/pull/188.  Thanks again!

**Comment by gdevenyi** [comment]
Thanks!

**Pull request closed without merging**
