### PR TITLE
styles upgrade

### PR DESCRIPTION
**Pull request by fmichonneau**
Bring the latest version of the lesson template.

* addresses #911

### CODE REVIEW

**Comment by deppen8** [comment]
Thanks, @fmichonneau! Can you give us a quick summary of what these changes will bring? `49 files changed` / `+1,564` / `−442` is tough to review line-by-line 😄  😓

**Comment by fmichonneau** [comment]
Yes, changes include:

- using GitHub Actions to run `make lesson-check-all` for PRs and commits
- more informative 404 page
- use a Gemfile to ensure that the environment used locally to preview the lesson is the same as the one used by GitHub Pages
- improvement to the Makefile
- use of Jekyll to create the "all in one" page instead of using JavaScript
- improvement and bug fixes for building the `relative_root_path` variable
- use anchors to link to headings in lessons
- include KaTeX for the rendering of mathematical notation
- add styling for additional language highlighting
- add a class for "warning" call outs
- improve the script for lesson checking
- update broken links
- improve language for clarity and accuracy

**Comment by deppen8** [comment]
@swcarpentry/shell-novice-maintainers, I did a quick look over these changes but I am not really qualified to look at Ruby or JS code. I tested the `make` commands and all seemed OK.

Anyone else want to take a peek before merging?

**Review by deppen8 — APPROVED** [review]

**Comment by gdevenyi** [comment]
>  am not really qualified to look at Ruby or JS code

Sadly I'm in the same place. As this comes from the SWC style devs, doesn't touch the lesson and has been deployed elsewhere, I figure we're fine for merge.

**Comment by deppen8** [comment]
Merging. YOLO! 🤞

**Pull request merged**
