### PR TITLE
Changed the body of Nelle's loop to only select her original datafiles

### PR DESCRIPTION
**Pull request by gracecox**
The original *[AB].txt matches Nelle's original data files and any newly created stats-$filename files as well. This results in an infinite loop that creates stats-$filename, stats-stats-$filename stats-stats-stats-$filename etc.

### CODE REVIEW

**Comment by gdevenyi** [comment]
Sorry, I'm not quite getting the problem here, the expansion of *[AB].txt is executed before goostats is run, so the list of files the loop runs over won't get larger.

If someone were to run the loop more than once that would be a problem.

Can you explain why you think this change is needed a bit more? Thanks.

**Comment by gracecox** [comment]
The loop is run more than once during the SWC lessons; once in the loops lesson and then again in the following lesson when Nelle creates her do-stats.sh shell script. The premise is that she made a mistake in her initial analysis and so uses a shell script to repeat it (but she doesn't remove the original set of stats- files first and so would get a set of stats-stats- files instead of the desired output). 

Since we get this undesired output when following the lessons exactly, I suggested a modification... Also, when I taught this lesson, several learners did run the script several times (with different parameters) and got confused about the files produced.

In general, I think it is more robust to write scripts so that they can be rerun without having to do other things first (i.e. remove a bunch of files). Does this make more sense? Thanks

**Comment by gdevenyi** [comment]
Okay, that sounds reasonable, however, all the loops before and afterwards look different. Can you update your PR to fix all instances, so the instructor doesn't have to explain why this one is different. Thanks.

**Comment by gdevenyi** [comment]
No response to request to uniformize changes. Please resubmit if updated.

**Pull request closed without merging**
