### PR TITLE
Update from core 2015 03 02

### PR DESCRIPTION
**Pull request by gvwilson**

### CODE REVIEW

**Comment by wking** [comment]
On Mon, Mar 02, 2015 at 09:10:24AM -0800, Greg Wilson wrote:
>   * Fix link to Pro Git chapter on contributing to a project.
>   * Do not render CONTRIBUTING.html. Ignore it if it is built.
>   * Merge pull request #179 from jdblischak/fix-pro-git
>   * Merge pull request #180 from jdblischak/ignore-contributing
>   * Add more lables to to setup labels script
>   * Merge pull request #176 from r-gaia-cs/core-add-more-labels

These are all in #91.

>   * Adding a contributor code of conduct
>   * Merge branch 'core' of github.com:swcarpentry/lesson-template into adding-contributor-covenant
>   * Ignoring CONDUCT.html
>   * Merge pull request #188 from gvwilson/adding-contributor-covenant
>   * Merging changes from lesson-template::core

And these are new since #91.

Do we drop #91 in favor of this PR?  Personally, I'd just leave it up
to the maintainers to merge from lesson-template's core branch, which
they should be following anyway.  That avoids overlapping PRs in a
15-hour window, and PRs going stale because the core branch keeps
moving forward.

**Comment by ChristinaLK** [comment]
Sorry, I merged #91 before looking at this.  :(  I will deal with the conflicts.  

I agree with @wking about making core merges (and possibly html updates?) the responsibility of a maintainer or dedicated contributor.  I'll need some hand-holding on what needs to happen with a core merge if that person is me...

**Comment by wking** [comment]
On Mon, Mar 02, 2015 at 03:01:25PM -0800, Christina Koch wrote:
> I'll need some hand-holding on what needs to happen with a core
> merge if that person is me...

I'm happy to help there.  If you're interested, ping me (here, or on
IRC, or via email) when you're ready to merge from core.  I don't
expect it to take more than a round or two of core merges before
you're flying solo most of the time.  If someone else wants to handle
the merges, or you have someone else to talk you through it, that's
fine with me too ;).

**Comment by ChristinaLK** [comment]
I'll send you an email - this will be a good project for tomorrow evening.

**Comment by gvwilson** [comment]
I can do this merge this morning if @ChristinaLK or @gdevenyi gives it 
the thumbs-up.

**Comment by ChristinaLK** [comment]
I was going to do it tonight, but if you want to do it yourself I won't stop you.  :)

For future reference, should the maintainer (or some other committed volunteer) be the one checking periodically for `core` updates and merging them in?

**Comment by gvwilson** [comment]
I'm hoping that core updates will be few and far between now that things 
are settling down, so we can handle them as a push from the center 
(i.e., when I've merged something significant into 
lesson-template::core, I can do a PR against the individual lessons 
affected).
Thanks,
Greg

**Pull request merged**
