### PR TITLE
add time estimates

### PR DESCRIPTION
**Pull request by ErinBecker**
Re: https://github.com/swcarpentry/shell-novice/issues/501

### CODE REVIEW

**Comment by gcapes** [comment]
I noted how long it took me to teach this lesson the last couple of times I taught it. Approx timings below:

1. 10
2. 30 + 10
3. 25 + 10
4. 30 + 20
5. 40 + 10
6. 30 + 15
7. 25 + 20

Which is 4:15 total excluding breaks. So my view of the current timings is that most of the episodes take longer than allotted, but some of the exercises take less time.

**Comment by gdevenyi** [comment]
Thanks @gcapes do you suggest any particular changes to this PR?

**Comment by gcapes** [comment]
@gdevenyi 
I would suggest changing the teaching + exercises timings to those above (unless someone strongly disagrees?). I appreciate that different groups/instructors will go at different paces, but my timings are based on a few deliveries of the lesson, and from experience the current 15 mins given for teaching each episode is way off.

**Comment by ChristinaLK** [comment]
I would be okay with using @gcapes times.  In that case, @ErinBecker could either update this PR or @gcapes could submit his own. @gcapes, if you're willing, go ahead.

**Comment by ErinBecker** [comment]
@gcapes thanks for taking these timings. I'd be happy to have my suggested timings updated to these. Can you put in a new PR and we'll close this one?

**Comment by gcapes** [comment]
Yep, no problem. Standby...!

**Comment by gdevenyi** [comment]
Closed in favour of #680

**Pull request closed without merging**
