### PR TITLE
Add filename output to clarify first loop example

### PR DESCRIPTION
**Pull request by ndporter**
Added "echo $filename" within initial loop example to make it easier to visualize in the output exactly where each line of output is coming from. While this adds a little complexity, it reduces potential for confusion.

<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.

You may delete these instructions from your comment.

\- The Carpentries
</details>

### CODE REVIEW

**Comment by deppen8** [comment]
I think I am in favor of this, but the "Follow the Prompt" section below the code box would need to be updated as well.

**Comment by knarrff** [comment]
With the new pull request mentioned above (against the original pull request) I attempted to fulfill the request by @deppen8. Please see if this is sufficient.

**Comment by ndporter** [comment]
That looks like it takes care of it. Thanks @deppen8 for the notice and @knarrff for the update. This looks ready to merge to me.

**Comment by bkmgit** [comment]
Thanks.

**Pull request merged**
