### PR TITLE
Consider adding "tree command"

### PR DESCRIPTION
**Pull request by Wolflab**
I decided to add the “tree” command to the Shell novice lesson. I am not 100% certain that this would be worth incorporating (maybe it will not work on all shell versions?). But I think it is a useful command for beginners who are trying to get a rough concept of directory structure. It is a nice stepping stone from the GUI folders to file paths. But mostly wanted show I can use github effectively to qualify as a software carpentry instructor.

### CODE REVIEW

**Comment by shwina** [comment]
I may be wrong, but `tree` requires special installation of the `tree` package. Also, is it available on Windows?

**Comment by Wolflab** [comment]
As far as I can tell, most newer shells are coming with the tree package, but it looks like several would need an install, making it less than ideal for software carpentry. That's a pity because I think the command is useful for beginners as well a s a good teaching tool. Oh well.

**Comment by shwina** [comment]
Couldn't agree more! :(

**Comment by gdevenyi** [comment]
Sadly tree isn't included in most Linux distros by-default, we'd like to stick to standard gnu/bsd tools included on the shell. ``find`` provides a (much uglier) alternative that can achieve similar goals and is included.

Thanks for your submission, maybe shell-extras might like it, but for now we'll have to decline for shell-novice.

**Pull request closed without merging**
