### PR TITLE
Created new instructions to setup identical environments for ALL less…

### PR DESCRIPTION
**Pull request by marskar**
…ons across Windows, MacOS and Linux using Anaconda or Miniconda; adapted UNIX lesson setup to use Jupyter QtConsole and/or Notebook

### CODE REVIEW

**Comment by shwina** [comment]
@marskar Thanks for this PR! However, I think that this PR belongs in https://github.com/swcarpentry/workshop-template/. @gdevenyi?

**Comment by gdevenyi** [comment]
Agree, this is for the style template

**Comment by marskar** [comment]
Good morning,
Sorry for the mistake.
OK, I will move this to workshop-template.
Cheers,
Martin

**Comment by shwina** [comment]
Thank you!

**Pull request closed without merging**
