### PR TITLE
Ep05: Add exercise to write first loop

### PR DESCRIPTION
**Pull request by eroesch**
Proposal as per issue #1244 for an exercise to learn how to write a loop.

<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.

You may delete these instructions from your comment.

\- The Carpentries
</details>

### CODE REVIEW

**Comment by gcapes** [comment]
Thanks for the PR. I like the idea of this, but think it would fit better immediately before the existing exercises here: https://swcarpentry.github.io/shell-novice/05-loop/index.html#variables-in-loops

That way the initial example has been fully explained, and a couple of examples have been shown before the learner is asked to write their own loop.

I would also rename `my_temporary_variable` to `loop_variable` to better reflect what this variable does.

**Comment by eroesch** [comment]
Hi. Yes, very happy with your suggestions. Would you like me to implement them, or do you want to do it?

**Comment by gcapes** [comment]
Would you like to do it? Thanks

**Comment by eroesch** [comment]
Sure thing. Easy. I'll do it right now and ping you.

**Comment by eroesch** [comment]
Done.

**Comment by gdevenyi** [comment]
Thanks!

**Pull request merged**
