### PR TITLE
callout for bash configuration

### PR DESCRIPTION
**Pull request by joshwaterfall**
Adding callout and link in 00-intro.md to Dalton Hubble's blog on Bash Configurations Demystified

### CODE REVIEW

**Comment by shwina** [comment]
@joshwaterfall @gvwilson 

Is `00-intro.md` really the right place for this? The article is short and informative, but by no means comprehensible for first time shell users. I'd vote for this to be placed in `discussion.md`.

**Comment by gvwilson** [comment]
+1 for moving it to discussion.md.

**Comment by joshwaterfall** [comment]
Good idea - I agree discussion is a better place.  I've moved it in my fork.  Can you pull it?

**Comment by shwina** [comment]
Thanks, @joshwaterfall - could you format it as a section instead of a callout?

**Comment by joshwaterfall** [comment]
@gvwilson I changed the formatting, how does it look now?

**Comment by shwina** [comment]
This looks better to me. I'd propose a sentence or two about what "configuring your bash" actually means and why you'd want to do it

**Comment by joshwaterfall** [comment]
I added such a sentence.  Let me know what you think.  Even a more detailed description might be useful but I feel this is a pretty good 'teaser' to justify clicking on the link.

**Comment by shwina** [comment]
Thanks @joshwaterfall 

@gvwilson, @gdevenyi - would you please weigh in on this?

**Comment by gdevenyi** [comment]
Looks reasonable. Thanks for the enhancement.

**Pull request merged**
