### PR TITLE
Fix #518  for 06-script

### LINKED ISSUE #518: Missing solutions to, context for, and files required by exercises
Many of the exercises don't have solutions. Some don't need solutions because learners can run the commands and see which is the correct answer. In some of the exercises, the commands can't be tested because the data files don't exist e.g. 07-find, "matching and subtracting" - there are no *ose.dat files

> The -v flag to grep inverts pattern matching, so that only lines which do not match the pattern are printed. Given that, which of the following commands will find all files in /data whose names end in ose.dat (e.g., sucrose.dat or maltose.dat), but do not contain the word temp?
> 
> find /data -name '*.dat' | grep ose | grep -v temp
> find /data -name ose.dat | grep -v temp
> grep -v "temp" $(find /data -name '*ose.dat')
> None of the above.

Sometimes it isn't clear which directory the question refers to.

I plan to submit a series of PRs to address these issues, using existing files as much as possible. Is this of interest to others?

### PR DESCRIPTION
**Pull request by gcapes**
Provide solutions and modify exercises to use the example data in data-shell.

### CODE REVIEW

**Comment by gcapes** [comment]
@shwina 
Just a bump, because there have been no comments on this yet.

**Comment by shwina** [comment]
I'm sorry, @gcapes - I'll get to this tonight.

**Comment by gcapes** [comment]
Oops! Yep, that's a mistake.
I'll rebase and fix it given it hasn't get been merged.
Cheers

**Comment by gcapes** [comment]
Ok, done!

**Comment by shwina** [comment]
Great! Thank you!

**Pull request merged**
