### PR TITLE
Make text dir paths resemble the images of those dirs

### PR DESCRIPTION
**Pull request by RobTheOceanographer**
This is part of the instructor training class in Melbourne.
I have made the text paths represent the image representations of those paths so that there is more consistency and flow to this part of the lesson.

### CODE REVIEW

**Comment by ChristinaLK** [comment]
Haha, this changes the text, this old PR #21 (unmerged) changes the image. Obviously a long-standing consistency problem!  I feel like the text should stay the way it is (b/c in the  next lesson, learners create `thesis` using `mkdir`), but I'll let others chime in on this.

**Comment by RobTheOceanographer** [comment]
Hi Christina, I don't mind which one is used but i think it would be good to merge one of these PRs so there is consistency in the lesson - maybe the image PR #21 change because, as you pointed out, the learners are asked to create the thesis when they get to mkdir.

**Comment by ChristinaLK** [comment]
Would you be able to copy/save that image and resubmit it as a new PR?  Don't feel obligated! - if you don't want to, I'll file it as an issue and someone will get round to it sooner or later.

**Comment by gvwilson** [comment]
@ChristinaLK your call whether to take this one or the older one that changes the image.

**Comment by ChristinaLK** [comment]
Closed -> changing imgs instead from PR #21, resubmitted in PR #105

**Pull request closed without merging**
