### PR TITLE
Small fixes to 05-script.md

### PR DESCRIPTION
**Pull request by nsoranzo**

### CODE REVIEW

**Comment by shwina** [comment]
Thanks, @nsoranzo!

**Comment by DanielBaird** [comment]
I also pull-req-ed a fix to the "ending with" language -- I switched it to "matches".
https://github.com/swcarpentry/shell-novice/pull/341

I considered this fix (changing to "ending with `.pdb`") but I thought keeping the `*.pdb` accurate to the text of the command made it super clear to learners which bit was being referred to.

**Comment by nsoranzo** [comment]
@DanielBaird I think that "ending with `.pdb` gives a better explanation, but I'm fine with both solutions.

**Comment by DanielBaird** [comment]
Closed #341 in favour of this.

**Pull request merged**
