### PR TITLE
Question demonstrating safe usage of rm.

### PR DESCRIPTION
**Pull request by pdoehle**
Hi, I'm going through the Software Carpentry instructor training and I thought it might be helpful to have a question demonstrating to students how to use rm with some safety built in.

### CODE REVIEW

**Comment by gvwilson** [comment]
Hi @shwina - can you please take care of merging this one? (I'm having no luck today merging patches.)

**Comment by shwina** [comment]
I'll get on it

**Comment by shwina** [comment]
This got merged:

https://github.com/swcarpentry/shell-novice/commit/bcf54af205d48cf32c47db3bdd37ea55c27979b5

But my git-foo is too weak to know why GitHub isn't resolving this as "merged"...

**Comment by gvwilson** [comment]
Assign it to me and I'll have a look tomorrow
Cheer,s
G

**Pull request closed without merging**
