### PR TITLE
remove judgmental language

### PR DESCRIPTION
**Pull request by ErinBecker**
Pointed out by a trainee at an instructor training workshop - some of the language in this episode is quite judgemental about using nano. This PR removes the judgmental language.

### CODE REVIEW

**Comment by jttkim** [comment]
two very minor suggestions: (1) how about "simplest" rather than "least complex" and (2) would it make sense to replace "are unintuitive" with "require more time to learn"?

**Comment by ErinBecker** [comment]
Great suggestions. I'm trying to avoid calling things "simple" as it
implies "easy" rather than "has fewer concepts/steps", which is what I'm
going for with "least complex".

I really like the change to "require more time to learn.

AFK now but will implement this when I get back to the ​computer. Thanks!

On May 18, 2017 5:05 PM, "Jan T. Kim" <notifications@github.com> wrote:

two very minor suggestions: (1) how about "simplest" rather than "least
complex" and (2) would it make sense to replace "are unintuitive" with
"require more time to learn"?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/swcarpentry/shell-novice/pull/570#issuecomment-302573789>,
or mute the thread

**Comment by ChristinaLK** [comment]
I like this change!

**Comment by gdevenyi** [comment]
Thanks!

**Comment by ErinBecker** [comment]
Thanks!

**Pull request merged**
