### PR TITLE
Dropping last challenge from page 04 on loops.

### PR DESCRIPTION
**Pull request by snim2**
This is a confusing question, as noted in several issues. This commit resolves Issue 99.

(This PR is related to the last training-course assignment)

### CODE REVIEW

**Comment by wking** [comment]
On Mon, Apr 20, 2015 at 08:17:46AM -0700, Sarah Mount wrote:
>   * Dropping last challenge…

+1 from me (obviously ;).

**Comment by snim2** [comment]
I'm happy to substitute for another question if people prefer...

**Comment by iglpdc** [comment]
+1 to dropping and not putting anything else, there's already enough challenges for that topic.

**Comment by ChristinaLK** [comment]
looks good to me!

**Pull request merged**
