### PR TITLE
Fix #518 for episodes 03 and 04

### LINKED ISSUE #518: Missing solutions to, context for, and files required by exercises
Many of the exercises don't have solutions. Some don't need solutions because learners can run the commands and see which is the correct answer. In some of the exercises, the commands can't be tested because the data files don't exist e.g. 07-find, "matching and subtracting" - there are no *ose.dat files

> The -v flag to grep inverts pattern matching, so that only lines which do not match the pattern are printed. Given that, which of the following commands will find all files in /data whose names end in ose.dat (e.g., sucrose.dat or maltose.dat), but do not contain the word temp?
> 
> find /data -name '*.dat' | grep ose | grep -v temp
> find /data -name ose.dat | grep -v temp
> grep -v "temp" $(find /data -name '*ose.dat')
> None of the above.

Sometimes it isn't clear which directory the question refers to.

I plan to submit a series of PRs to address these issues, using existing files as much as possible. Is this of interest to others?

### PR DESCRIPTION
**Pull request by gcapes**
More to follow - is it easier if I create a new PR for each episode? Or would you rather I keep all these changes together?
Cheers
G

### CODE REVIEW

**Comment by shwina** [comment]
Smaller PRs would be much better going forward - thank you!

**Comment by shwina** [comment]
Also, I see that the commit from #519 is here as well. Do you want to close that PR?

**Comment by gcapes** [comment]
My mistake - I branched at the wrong point. I can close PR #519, or fix it and remove the commit from this PR. If you need me to split this PR, please let me know, and I'll give that a go. Otherwise, I'll just stop adding to it, and instead reference the issue number I'm fixing when I submit new, separate PRs for  episodes 5/6/7.

**Comment by gcapes** [comment]
I'll close this, and open 3(+) separate pull requests, grouping the changes to each episode.

**Comment by shwina** [comment]
Thanks!

**Pull request closed without merging**
