### PR TITLE
02:Clarification of single quotes on PS1='$ '

### PR DESCRIPTION
**Pull request by mjones01**
Current description doesn't specify why the quotes are needed (and the aren't if you don't also want the space after $.  
I asked Greg about this during my instructor demo today and he suggested that it could be better clarified.

### CODE REVIEW

**Comment by gdevenyi** [comment]
Hi, were there questions in during a lesson that prompted this addition? It feels a bit like excess information.

**Comment by mjones01** [comment]
No, I haven't taught this lesson yet.  I did this for my instructor checkout lesson with Greg Wilson and asked him why the quotes were needed as I was just doing PS1=$ and it seemed to work -- I hadn't realized that there was a space after the $.  He suggested that I suggest of change to clarify.  Feel free to ignore if you don't think it is necessary.

**Comment by rgaiacs** [comment]
@mjones01 Thanks for the lesson. The change looks good to me since we didn't introduce yet the concept that strings with space need quotes. I would only ask that you use `$` instead of $.

**Comment by mjones01** [comment]
@rgaiacs Done!  Thanks.

**Comment by shwina** [comment]
I agree with @gdevenyi that this is excess information, and doesn't really explain itself too well. I think it's more important that we say: "Don't forget the empty (space) character after the `$` sign".

**Comment by shwina** [comment]
@mjones01 - thoughts?

**Comment by mjones01** [comment]
As it seems like others find little need for this change, I'm happy to close the PR. Or I can revise to @shwina 's suggestion.  
In alignment with the Discuss listserv from today/yesterday, this change is probably only relevant to independent learners who come across the lessons, not those in the workshop as the instructor will likely say what what they are doing when they do this.

**Comment by gdevenyi** [comment]
I think we can leave this for now.

**Pull request closed without merging**
