### PR TITLE
Changing /home to / users.

### PR DESCRIPTION
**Pull request by ocefpaf**
Partially solves #124.

PS: I am unsure if Mac uses `/Users` or `/users`.

### CODE REVIEW

**Comment by r-gaia-cs** [comment]
> PS: I am unsure if Mac uses `/Users` or `/users`.

AFAIR is `/Users`.

**Comment by iglpdc** [comment]
Yep, /Users.

**Comment by ocefpaf** [comment]
Thanks @iglpdc and @r-gaia-cs I think I got all `/users`.

**Comment by r-gaia-cs** [comment]
@ocefpaf Can you squash this pull request? You asked me early today if squash the commits are required and I said no. It isn't but I think is something good in this case, i.e. having only one commit changing from `/home` to `/Users` instead of two commits.

**Comment by ocefpaf** [comment]
@r-gaia-cs done.

**Pull request merged**
