### PR TITLE
Correct internal link text for renamed chapters.

### PR DESCRIPTION
**Pull request by Ry4an**
URLs don't change (to avoid broken inbound links), but the chapter title
link text needed updating.  Addresses swcarpentry/shell-novice#199 continuing swcarpentry/shell-novice#378

### CODE REVIEW

**Comment by shwina** [comment]
Can we also change the filename "01-filedir" and "02-create" to something more reflective of the new titles? I would propose `01-navigating.md` and `02-filedir.md`. As an aside, I think that "Navigating the file system"/"Navigating the filesystem" may be more appropriate for section 1 - any thoughts?

**Comment by shwina** [comment]
I see your point. This being the first section, it's probably not a great idea to use the term "filesystem". My initial suggestion was for something like "Finding Your Way Around". It's friendlier and more accurate than the current "Navigating Diles and Directories". I'm uncomfortable with the notion of "navigating files". Perhaps "Browsing Files and Directories" is also OK.

**Comment by shwina** [comment]
Perhaps changing file names and breaking URLs should be a separate issue. Thanks so much for raising these important points.

**Comment by Ry4an** [comment]
I like "finding your way around" a lot. 

I'll add renaming to the pr and we'll see if anyone objects. :) 

On June 7, 2016 5:29:37 PM EDT, Ashwin Srinath <notifications@github.com> wrote:
>I see your point. This being the first section, it's probably not a
>great idea to use the term "filesystem". My initial suggestion was for
>something like "Finding Your Way Around". It's friendlier and more
>accurate than the current "Navigating Diles and Directories". I'm
>uncomfortable with the notion of "navigating files". Perhaps "Browsing
>Files and Directories" is also OK. 
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/swcarpentry/shell-novice/pull/379#issuecomment-224420358

-- 
tYoped on a tiny keyboard.

**Comment by gdevenyi** [comment]
This is good as-is. We need to be quite careful adjusting filenames as to not break external links, many of which we may not have control of.

**Pull request merged**
