### PR TITLE
Update style to v9.1.1

### PR DESCRIPTION
**Pull request by rgaiacs**
A few changes on style.

### CODE REVIEW

**Comment by gdevenyi** [comment]
Should we close in favour of v9.1.2?

**Comment by rgaiacs** [comment]
> Should we close in favour of v9.1.2?

I created v9.1.2 to be friendly with @gcapes, https://github.com/swcarpentry/make-novice/pull/81#issuecomment-286360863. All this release process is super new to everyone and I want to void pull requests every week but I still want to make our virtual space friendly and welcome.

If you want I can update this pull request with v9.1.2. It will cost me less than five minutes. But I believe that we will change https://github.com/swcarpentry/styles/pull/139/commits/12506a4b66016088a5c8582ac6e34ccb2cdb13f3 in the next few months so I not bother too much about it.

**Comment by gdevenyi** [comment]
Okay, this one is fine then. Thanks!

**Comment by gdevenyi** [comment]
Haven't heard of any issues after incubating so will merge!

**Pull request merged**
