### PR TITLE
Update redirects-and-pipes.svg

### PR DESCRIPTION
**Pull request by marwahaha**
How do I make a PNG? Could someone help with this?

fixes https://github.com/swcarpentry/shell-novice/issues/529

### CODE REVIEW

**Comment by shwina** [comment]
Thank you!

I've used tools such as ImageMagick (https://www.imagemagick.org/script/index.php) and Inkscape (https://www.imagemagick.org/script/index.php) for this. For a single file, perhaps something like this:

https://cloudconvert.com/svg-to-png

Just tried with this SVG and pretty happy with the result:

index

**Comment by shwina** [comment]
Hi @marwahaha , any possibility of updating this PR?

**Comment by marwahaha** [comment]
You can take it over!

**Comment by marwahaha** [comment]
@shwina -- I used the image you posted here -- It's a bit smaller than the older image.

**Comment by shwina** [comment]
Thanks very much!

**Pull request merged**
