### PR TITLE
Fix north-pacific-gyre hierarchy

### PR DESCRIPTION
**Pull request by HepoH3**
After c24e2624 Nelle's samples files processed as if they were placed directly in 'north-pacific-gyre' (see listing below), while right now they placed in '[2012-07-03](https://github.com/swcarpentry/shell-novice/tree/main/filesystem/Users/nelle/north-pacific-gyre/2012-07-03)' subdirectory. Running this commands will produce an error instead of 18 lines of result.

https://github.com/swcarpentry/shell-novice/blob/18318bea5426c791fabb474512f58fc9348197d4/episodes/04-pipefilter.md?plain=1#L628-L648

_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._

_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._

_If any relevant discussions have taken place elsewhere, please provide links to these._

<details>

For more guidance on how to contribute changes to a Carpentries project, please review [the Contributing Guide](CONTRIBUTING.md) and [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html).

Please keep in mind that lesson Maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum. If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The Carpentries Team at team@carpentries.org.

</details>

### CODE REVIEW

**Comment by HepoH3** [comment]
I found out that there are two `north-pacific-gyre` dirs:

- `/shell-lesson-data/north-pacific-gyre`
- `/filesystem/Users/nelle/north-pacific-gyre`

The first one already contains this files as expected (without `2012-07-03` directory). As I see now, the exercise should be executed using this folder. However, I'm a bit confused: what is the `filesystem` directory for, then? Should it be consistent with the `shell-lesson-data` directory? If so, this PR still applies.

**Comment by bkmgit** [comment]
Thanks for the pull request. Checking it.

**Comment by gcapes** [comment]
There should be a zip file to download, which contains the `shell-lesson-data` directory. This is what learners should be using to follow the lesson (detailed on the [setup page](https://swcarpentry.github.io/shell-novice/index.html#download-files)). It looks like there are also some legacy pages left around which could maybe be removed? It doesn't look like the `filesystem` directory is used for anything(?)

When these lessons moved over to being built with R, it looks like the `makefile` was deleted but it contained a rule to make the zip file, which was
```
##
## Shell lesson specific commands
## =================================================

ZIPFILE = data/shell-lesson-data.zip

.PHONY : zip
## zip              : create zip file for learners to download
zip : shell-lesson-data
	zip -r -FS $(ZIPFILE) $<
```

I've had a quick search through the lesson material and I don't think there's a `2012-07-03` directory mentioned, so I *think* it's all good how it is?

**Comment by HepoH3** [comment]
Okay, I think I should close this PR then😅

**Pull request closed without merging**
