### PR TITLE
Added Bloom's Taxonomy labels to learning objectives in all topic files

### PR DESCRIPTION
**Pull request by alixk**
As part of instructor training checkout.

### CODE REVIEW

**Comment by gdevenyi** [comment]
Hi,

Can you explain your motivation for adding this? I don't think the other lessons currently implement this.

**Comment by gvwilson** [comment]
I suggested this as one of the things people could do for instructor 
training - we'd like to label all learning objectives eventually.

**Comment by gdevenyi** [comment]
Interesting. I'd like to see some motivating mention in the introduction of what this taxonomy is and why its helpful.

**Comment by gvwilson** [comment]
We cover it in instructor training these days - see 
http://swcarpentry.github.io/instructor-training/19-lessons/

**Comment by gdevenyi** [comment]
Huh, maybe I should take training again. Thanks.

**Comment by gvwilson** [comment]
If you get McGill to sign up as a partner, I'll come and do training in 
Montreal and you can sit in :-)

**Comment by gdevenyi** [comment]
or the Douglas, or MNI, or Calcul Quebec, or QBIN...

One day...

**Comment by gvwilson** [comment]
We get Calcul Quebec as part of the Compute Canada deal, but if you can 
sign up the other three, there's a t-shirt in it for you :-)

**Pull request merged**
