### PR TITLE
Update 02-filedir.md

### PR DESCRIPTION
**Pull request by dhanyapushpadas**
Fixed issue #1264 [1264](https://github.com/swcarpentry/shell-novice/issues/1264)

### CODE REVIEW

**Comment by gcapes** [comment]
Thanks for the PR. 

The thing with bold is that it's easily overdone. I think that with the warning above the bullets already bold, this extra bold isn't needed. 

@swcarpentry/shell-novice-maintainers 
Any thoughts?

**Comment by deppen8** [comment]
@dhanyapushpadas, GitHub tells me it is your first GitHub pull request. Congrats! 🎉 And thanks for contributing to this lesson!

On the content of the lesson, I agree with @gcapes: the disclaimer is there in bold above and repeated again in normal text, which should be sufficient. 

Since you brought it to our attention though, I do find the current wording a bit awkward with the parenthetical breaking up the text in an odd place. Perhaps there is some other way to clean up the text and raise the disclaimer in a smoother fashion. I'd be happy to look at some suggestions, if you have any ideas.

**Comment by dhanyapushpadas** [comment]
@gcapes @deppen8 Thank you for the comments, with further thinking I too agree with your points. I don't have any better suggestion,  but I have experienced that this is not visible enough to some learners. Probably by linking the text to the reason why it is not available or making a note , we can differntiate this?

**Comment by deppen8** [comment]
I am closing this PR because of inactivity, but happy to re-open if there is further appetite for making changes here.

**Pull request closed without merging**
