### PR TITLE
Issue828 rearrangements in working with files

### PR DESCRIPTION
**Pull request by schmeing**
Did part of what was suggested in Issue #828 "Suggested edit to a lesson"

I moved up the "Good names for files and directories" and "What’s in a name?" boxes. However, not completely up to the first sentence as I think it helps to visually see some examples and the ls -F command two lines after does exactly that.

The "Which Editor?" box I left untouched as I think it is overloading the students to put all that info before you are using it, so I left it right in front of the first use of the nano editor.

### CODE REVIEW

**Comment by colinmorris** [comment]
Thanks for the PR (and sorry for the late response). Moving that key point from lesson 2 to 3 is definitely a great correction.

I'm ambivalent on rearranging the info boxes in this way though. I tend to think of content in the 'callout' boxes as optional or supplementary, so I think it makes sense to put them after the main content to which they're relevant. e.g. to have an example of creating a file or directory, then have a callout box with tips on naming style.

I'd be curious to hear other perspectives on this though.

**Comment by gcapes** [comment]
Thanks for the contribution @schmeing 
I agree with @colinmorris  that the current position of the callouts makes sense - in general the lessons  do something first, then expand on it when the learner has something to 'hang' the new information on. 

If everyone agrees, could you reset your branch so that the PR only includes commit https://github.com/swcarpentry/shell-novice/pull/871/commits/02296dfe11e28bfe7030b8cc7beacb630fe44656. Do shout if you're unsure about the git side of things.

**Comment by schmeing** [comment]
Reverted the 2 commits as asked during the merge with the base
I still think "What's in A Name" and "Good names for files and directories" belong together as they are both about how to name files and directories.
The advantage of having the "What's in A Name" at the same position where "Good names for files and directories" currently is, is that there are multiple examples of file endings and not just .txt shown in the ls.
The disadvantage is that it would be a huge chunk of additional information right there.

**Comment by gcapes** [comment]
Thanks @schmeing.

I see no reason not to move the `What's in a name` callout into the `Create a text file` section. I don't think it should go right after the `Good names for files and directories` callout because it only refers to files, and at this point I think we need to be careful to avoid cognitive overload.

I have a large PR (#887) waiting review, which fixes several issues - I'll tag this suggestion onto that.

**Comment by gcapes** [comment]
Reset and merged in f82338e80d9d9dfee82a569032e3acfaef060c2e

**Pull request closed without merging**
