### PR TITLE
Add in a diagram showing redirects and pipes

### PR DESCRIPTION
**Pull request by jpallen**
Based on an initial discussion in swcarpentry/bc#817. I've modified the diagram quite a lot since then, but I think this version is clearer and more descriptive. It also fits in better with the discussion comparing redirects and pipes towards the end of the lesson rather than with the examples earlier on.

### CODE REVIEW

**Comment by gvwilson** [comment]
@jpallen can you please resubmit? I like the diagram, but we need it on top of all the changes.

**Comment by synapticarbors** [comment]
@gvwilson I'm happy to help out if I can, but I want to make sure that I haven't been assigned this in error since I haven't been involved with this PR previously.

**Comment by gvwilson** [comment]
If you have time, we'd be grateful for your input.

**Comment by synapticarbors** [comment]
@gvwilson I'm going to need an explanation of what needs to be done since I can't intuit it from looking at the comment thread and there are a lot of commits/file changes mixed in with this.

**Comment by jpallen** [comment]
I need to resubmit this on top of the new history I think. I will do that ASAP. I need to figure out what I was thinking when I first submitted it first though, sorry for the delay.

**Comment by gvwilson** [comment]
@jpallen can you please resubmit this?  Or mail the image to one of us and we'll do so?

**Comment by jpallen** [comment]
Done, sorry for the delay.

**Comment by ChristinaLK** [comment]
@jpallen sorry to ask for another re-commit, but can you submit this on top of the gh-pages branch?

**Comment by jpallen** [comment]
Done in #98.

**Pull request closed without merging**
