### PR TITLE
02-filedir.md Wording change for change directory command

### PR DESCRIPTION
**Pull request by AndreasBilke**
Reuse the phrase "current working directory" since this is introduced at the beginning of the episode.

### CODE REVIEW

**Comment by bkmgit** [comment]
Thanks for the contribution.

**Comment by gcapes** [comment]
I think a combination of both would be useful. e.g.
"it changes the shell's idea of what directory we are in i.e. it changes the current working directory"

**Comment by AndreasBilke** [comment]
@gcapes As suggestest I kept the old phrase and extend it with a new description.

**Review by gcapes — CHANGES_REQUESTED** [review]
Could you please break the long line 392 at the end of the first sentence. 
Otherwise the automated checks will prevent the PR from merging.

**Comment by AndreasBilke** [comment]
> Could you please break the long line 392 at the end of the first sentence. Otherwise the automated checks will prevent the PR from merging.

Like that?

**Review by gcapes — APPROVED** [review]

**Pull request merged**
