### PR TITLE
Remove rmdir, since no one really uses it

### PR DESCRIPTION
**Pull request by gdevenyi**
Addresses #337

### CODE REVIEW

**Comment by Mahdisadjadi** [comment]
This is very good now!

**Comment by shwina** [comment]
Maybe link to the [recursion](https://en.wikipedia.org/wiki/Recursion) wiki page? Learners may not be familiar with this term..

**Comment by vfaghirh** [comment]
I usually make and remove several directories during my computational work, but I usually use rm -r to remove a directory. In general I think it is good to tell the readers how they can remove a directory and also give them several options for doing that. So I do not agree with removing this from the lessons, I think it could be useful to some people.

**Comment by wking** [comment]
On Mon, Jun 13, 2016 at 11:08:04AM -0700, vfaghirh wrote:
> So I do not agree with removing this from the lessons, I think it
> could be useful to some people.

While I agree with @vfaghirh that rmdir is useful to some people (I
use it frequently), I also agree with the folks in #337 that it's
probably not useful enough to be worth teaching an additional command
in the learner's first four hours of shell.  So I'm fine removing it
(although pointing novices at ‘rm -r’ makes me jumpy ;).

**Comment by gdevenyi** [comment]
@wking exactly why the callout stayed and discussed interactive mode :)

**Comment by gdevenyi** [comment]
Addressed @shwina ' s suggestion of a link to wikipedia.

**Comment by shwina** [comment]
+1 from me.

**Comment by gdevenyi** [comment]
Great, merging

**Pull request merged**
