### PR TITLE
pull request post #t3davis, added coreutils

### PR DESCRIPTION
**Pull request by seanpue**
Added coreutils as option for Windows. This is a post-#t3davis pull request, so can be ignore. Though it might be a good option as it adds Unix commands to Windows shell.

### CODE REVIEW

**Comment by r-gaia-cs** [comment]
@seanpue Thanks for the pull request. To add more commits to your pull request just

~~~
$ git push origin gh-pages
~~~

The pull request will be automatically update to include the new commits that you push.

Could you run

~~~
$ git reset HEAD~
$ git commit -a --amend
$ git reset HEAD~
$ git commit -a --amend
$ git push -f origin gh-pages
~~~

This commits will squash the commits into one single commit and update this pull request.

**Comment by gdevenyi** [comment]
Have you tested the coreutils installs? We rely heavily on the bashisms for looping and other things, and I think coreutils provides command line unix-like utilties *for* the windows cmd.exe shell.

**Comment by stefanv** [comment]
@gvwilson Did you intend to assign me to this issue?

**Comment by gvwilson** [comment]
On 2015-02-02 3:48 PM, Stefan van der Walt wrote:
>
> @gvwilson <https://github.com/gvwilson> Did you intend to assign me to 
> this issue?
>
Yes - if you have a couple of minutes to look it over, I'd be grateful.  
If not, please assign it back to me and I'll look for someone else.

Cheers,
Greg

**Comment by gdevenyi** [comment]
My concerns with this stand on the coreutils vs. bashisms, I'm not sure coreutils gives a full POSIX environment.

**Comment by stefanv** [comment]
I agree with @gdevenyi that coreutils by itself is not enough to provide an environment--you at least also need to install a modern shell (it doesn't look as though coreutils provides bash, e.g.).

Do we have a script for testing all the shell capabilities used during SWC workshops?  That would make it easy to evaluate any Windows environment.

**Comment by wking** [comment]
On Mon, Feb 02, 2015 at 02:26:04PM -0800, Stefan van der Walt wrote:
> Do we have a script for testing all the shell capabilities used
> during SWC workshops?  That would make it easy to evaluate any
> Windows environment.

The installation test script just looks for one of a few whitelisted
shells [1,2].  If there's a POSIX shell that's not listed in that
check, it should be easy to add support for it, but I don't think we
want to build our own POSIX-shell-compliance test suite.

[1]: https://github.com/wking/swc-setup-installation-test/blob/d13b26c9fb89beebe9ff9e9dfc86ba8ddb8d01cd/swc-installation-test-2.py#L866
[2]: http://git.tremily.us/?p=swc-setup-installation-test.git;a=blob;f=swc-installation-test-2.py;h=16532ffc4a56cae5633d4f644a39e40a68c2667e;hb=d13b26c9fb89beebe9ff9e9dfc86ba8ddb8d01cd#l866

**Comment by stefanv** [comment]
@wking Perhaps `sh` should be removed from that list, then it would be a better check for a usable environment.

**Comment by wking** [comment]
On Mon, Feb 02, 2015 at 04:14:58PM -0800, Stefan van der Walt wrote:
> @wking Perhaps `sh` should be removed from that list, then it would
> be a better check for a usable environment.

Why?  `sh` should be POSIX-compliant, no?

**Comment by stefanv** [comment]
I was going on what @gdevenyi pointed out above--that a lot of bash-isms (loop constructs) are being taught, so unless a learner has BASH or something like it, they might struggle.

**Comment by wking** [comment]
On Mon, Feb 02, 2015 at 04:33:41PM -0800, Stefan van der Walt wrote:
> I was going on what @gdevenyi pointed out above--that a lot of
> bash-isms (loop constructs) are being taught, so unless a learner
> has BASH or something like it, they might struggle.

I don't think we do (or should) teach anything Bash-specific.  Loops
are in POSIX [1], so they're fine.

[1]: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09_04_03

**Comment by stefanv** [comment]
`sh` does not have tab completion, paths are often not set up, no ansi color--it would be a nightmare to teach someone using raw `sh`.

Either way, @seanpue can you verify that `coreutils` by itself fulfills the requirements of the installation script?

**Comment by gvwilson** [comment]
On 2015-02-03 1:24 PM, Stefan van der Walt wrote:
>
> |sh| does not have tab completion, paths are often not set up, no ansi 
> color--it would be a nightmare to teach someone using raw |sh|.
>

+1.

**Comment by wking** [comment]
On Tue, Feb 03, 2015 at 10:24:42AM -0800, Stefan van der Walt wrote:
> `sh` does not have tab completion, paths are often not set up, no
> ansi color--it would be a nightmare to teach someone using raw `sh`.

I'm not sure about “paths are often not set up”.  It should be using
your system PATH like every other shell.  Obviously, you're not going
to get any PATH tweaks from ~/.bash_profile, but then neither will
folks running dash.  Tab completion and ANSI colors are nice, but not
*critical*.  I'd certainly recommend folks use Bash or another
extended shell, but if someone shows up with a pure POSIX shell (or an
unlisted shell that also supplies `sh` as a limited symlink,
e.g. BusyBox), they should still be able to follow along.

> Either way, @seanpue can you verify that `coreutils` by itself
> fulfills the requirements of the installation script?

I'm pretty sure that the GNU Core Utilities has a bunch of the
external commands [1] but doesn't actually have a shell.

[1]: http://en.wikipedia.org/wiki/GNU_Core_Utilities

**Comment by stefanv** [comment]
Then I guess we can close this one?

**Comment by wking** [comment]
On Tue, Feb 03, 2015 at 12:27:21PM -0800, Stefan van der Walt wrote:
> Then I guess we can close this one?

I wouldn't be surprised if “GNU Core Utilities + a POSIX shell” worked
fine.  That's probably a lighter weight dependency than Git for
Windows, and is certainly a lighter-weight dependency than Cygwin.
Folks looking for a more native experience on Windows may be
interested too.  I just don't know if folks are distributing
pre-compiled POSIX shells for Windows *without* bundling in the core
utilities.

**Comment by stefanv** [comment]
@seanpue Can you test whether (WinBash)[http://win-bash.sourceforge.net/] + Coreutils does the trick?

**Comment by wking** [comment]
On Sat, Feb 07, 2015 at 06:27:14PM -0800, Stefan van der Walt wrote:
> @seanpue Can you test whether WinBash + Coreutils does the trick?

Just FYI, the FAQ on [1] has:

  First of all, you should keep in mind that win-bash is based on a
  old version of bash (1.14.2) while cygwin-bash is more or less up to
  date.

it looks like 1.14.2 came out around 1995-01-04 [2], so it's even
older than version bundled by OS X ;).  The rest of the FAQ explains
that the win-bash authors haven't noticed any incompatibilities, but
folks may miss some features that other Bash users have had for twenty
years (!).

On the other hand, as long as we stick to POSIX in the lessons, I
don't expect any serious problems.

[1]: http://win-bash.sourceforge.net/#faq
[2]: https://ftp.gnu.org/gnu/bash/

**Comment by stefanv** [comment]
We can agree that it's better than `sh`, though :)

**Comment by gvwilson** [comment]
So, merge or not?

**Comment by gdevenyi** [comment]
Not merging, this fractures our install base even more than OSX/Win/Linux already does and will be crazy to support and @seanpue hasn't provided any testing or response since the original PR.

**Pull request closed without merging**
