### PR TITLE
Lesson contribution: add reference to _episodes in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by BinxiePeterson**

### CODE REVIEW

**Comment by iglpdc** [comment]
It's a good change, but shouldn't be this part of the lesson-template repo so we get it in the other lessons as well?

**Comment by shwina** [comment]
Agreed with @iglpdc, I think the correct place to open a PR would be:

https://github.com/swcarpentry/lesson-example/blob/gh-pages/CONTRIBUTING.md

**Comment by BinxiePeterson** [comment]
Agreed. Opened a PR in https://github.com/swcarpentry/lesson-example/blob/gh-pages/CONTRIBUTING.md as suggested.

**Comment by shwina** [comment]
Thanks a lot, can we close?

**Comment by gvwilson** [comment]
Yes please - Ivan, can you please walk Bianca through the steps to get 
it in there?

**Comment by iglpdc** [comment]
I think she did already: 
> Agreed. Opened a PR in https://github.com/swcarpentry/lesson-example/blob/gh-pages/CONTRIBUTING.md as suggested.

**Pull request closed without merging**
