### PR TITLE
Fixing (most) problems in 04-loop.md

### PR DESCRIPTION
**Pull request by gvwilson**
Addresses most of #28.

"Nelle's Pipeline" is a good use case for a level-2 heading inside a lesson...

### CODE REVIEW

**Comment by wking** [comment]
On Tue, Mar 03, 2015 at 07:34:52AM -0800, Greg Wilson wrote:
>   * Fixing (most) problems in 04-loop.md

This replaces some of the challenge titles, which I'd tried to address
in #33.  I've never been clear on why #33 was closed [1], but I prefer
my:

  Nested loop reading comprehension

and:

  Leading variable reading comprehension

to this PR's:

  Command-Line Expressions

and:

  Explain This Loop

[1]: https://github.com/swcarpentry/shell-novice/pull/33#issuecomment-72404111

**Comment by ChristinaLK** [comment]
Is there a protocol for level 2 vs level 1 (or 3) headings?  

@wking, including "reading comprehensions" in the title of a challenge seems a bit daunting to me, mostly because I think you mean it quite literally (as in, can you read + comprehend this), but I would conflate it w/ more technical ideas about "reading" (files) and comprehensions (lists in python).  Not sure a novice would have those associations, but I think short/simple words are best for titles in this situation.  

@gvwilson My pedantic nature would suggest including "nested loops" or "multiple loops" in the title of the "command line expressions" challenge (because that seems to be the real focus of the challenge).  Thoughts?

Otherwise looks good.

**Comment by wking** [comment]
On Tue, Mar 03, 2015 at 07:14:46PM -0800, Christina Koch wrote:
> Is there a protocol for level 2 vs level 1 (or 3) headings?  

The lesson-template docs [1] use level 2 headings for blockquotes
(which we use for learning objectives, challenges, and callouts).
They also say: “There are no sub-headings inside a topic other than
the ones shown. (If a topic needs sub-headings, it should be broken
into two or more topics.)”

> @wking, including "reading comprehensions" in the title of a
> challenge seems a bit daunting to me, mostly because I think you
> mean it quite literally (as in, can you read + comprehend this), …

Yeah.

> … but I would conflate it w/ more technical ideas about "reading"
> (files) and comprehensions (lists in python).

Yikes ;).  Maybe I just took too many reading comprehension tests
growing up ;).

> Not sure a novice would have those associations, but I think
> short/simple words are best for titles in this situation.

We can probably find something that works for everyone ;).  How about
we just drop the troublesome phrase and have:

  Nested loops

and:

  Leading variables

?

As I pointed out in #33, I'd rather just drop the last challenge,
because I don't think it belongs in the loop section.  If we keep it,
it would be nice to at least have some notes in instructors.md
explaining what students are supposed to be learning, and why the
challenge is lurking in the loop section.

[1]: https://github.com/swcarpentry/lesson-template/blob/966a0322695852676884f8c094b83d31cc4c728c/LAYOUT.md#topics

**Comment by gvwilson** [comment]
Changes made based on feedback.

**Comment by wking** [comment]
On Wed, Mar 04, 2015 at 05:07:15AM -0800, Greg Wilson wrote:
> Changes made based on feedback.

If you want to highlight `expr`, maybe:

  Nested Loops and Command-Line Expressions

could be:

  Nested Loops and `expr`

bash(1) talks about expressions for ((…)) (arithmetic), [[…]]
(conditionals), {x..y[..incr]} (sequences), ….  Wikipedia's definition
for “expression” matches pretty much everything listed in bash(1)'s
SHELL GRAMMAR section (simple commands, pipelines, lists, compound
commands, …).  I'd rather be explicit and just mention `expr`
directly.

I'm also still not clear on the purpose of the last challenge [2].
Should I open a new PR for that discussion?

[1]: http://en.wikipedia.org/wiki/Expression_%28computer_science%29
[2]: https://github.com/swcarpentry/shell-novice/pull/95#issuecomment-77091277

**Comment by ChristinaLK** [comment]
@wking I think a new PR (or issue) about last challenge is appropriate.

**Comment by wking** [comment]
On Wed, Mar 04, 2015 at 08:27:17PM -0800, Christina Koch wrote:
> I think a new PR (or issue) about last challenge is appropriate.  

Done in #99.

**Pull request merged**
