### PR TITLE
Added two exercises to 06-find/

### PR DESCRIPTION
**Pull request by cfgauss**
This is part of the completion of Software Carpentry instructor training.

### CODE REVIEW

**Comment by gvwilson** [comment]
Thanks for the pull request - can you please mail Greg Wilson with the 
link?  (Don't know which human corresponds to the 'cfgauss' account.)

**Comment by cfgauss** [comment]
Sorry for the anonymity. I added two exercises to 06-find in shell-novice.
-Bill McClung

**Comment by gvwilson** [comment]
Thanks,
Greg

**Comment by gcapes** [comment]
Thanks for the PR @cfgauss!

These are great exercises (for advanced learners)! 

Unfortunately, given how long this PR has been open, the formatting of the lesson and the contents of the `molecules` directory has changed a bit, and it would also be good to have a solution. Would you be interested in updating this PR, or should I finish it for you? 

I would be tempted to merge the questions, because part 2 ,while useful, consolidates earlier material rather than the `grep`/`find` material.

The solution below works - is this what you had in mind?

```
for file in *.pdb
	do
		echo -n $file " "
		grep -c ATOM $file
	done | sort -k 2 -n
```

**Comment by cfgauss** [comment]
@gcapes I agree that this PR is "old" and doesn't pertain to the current version of the lesson. Your solution is what I had in mind if you decide to include a merged question. I'd be happy to close the pull request if you wish.

**Comment by cfgauss** [comment]
Exercise has been commited to 07-find.

**Pull request closed without merging**
