### PR TITLE
move exercise - Variables in Shell Scripts

### PR DESCRIPTION
**Pull request by ErinBecker**
Moves "Variables in Shell Scripts" exercise from end of episode to before discussion of history.

### CODE REVIEW

**Comment by gdevenyi** [comment]
Hi, there's been a slight code drift here, can you  please rebase?

**Comment by ErinBecker** [comment]
@gdevenyi - I actually don't know how to do that. Could you point me towards directions?

**Comment by ErinBecker** [comment]
I tried using the instructions given by GitHub (above), but got the following error. I can make a new PR if required, just let me know.

~~~
Erins-MacBook-Air-2:shell-novice ebecker$ git checkout -b ErinBecker-06-scripts-patch-3 gh-pages
Switched to a new branch 'ErinBecker-06-scripts-patch-3'
Erins-MacBook-Air-2:shell-novice ebecker$ curl -L https://github.com/swcarpentry/shell-novice/pull/668.patch | git am -3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   150    0   150    0     0    423      0 --:--:-- --:--:-- --:--:--   457
100    32    0    32    0     0     44      0 --:--:-- --:--:-- --:--:--    44
Patch is empty. Was it split wrong?
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
~~~

**Comment by gdevenyi** [comment]
Weird:
```
curl -L https://github.com/swcarpentry/shell-novice/pull/668.patch
Sorry, this diff is unavailable
```

Can you please do a new PR for this one I guess? Sorry!

**Pull request closed without merging**
