### PR TITLE
Update 03-create.md to include whitespace definition

### PR DESCRIPTION
**Pull request by kagross**
Including a definition for whitespace the first time that it comes into play in the lesson could erase some confusion for students that don't know the word.

Please delete the text below before submitting your contribution. 

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck (k8hertweck@gmail.com).  

---

### CODE REVIEW

**Comment by gdevenyi** [comment]
Thanks for the addition, can you maybe wrap this in a callout box?

**Comment by colinmorris** [comment]
These changes are actually inside a callout box already (under the heading "Good names for files and directories"). I don't think they can be nested.

What if we replaced "whitespace" with "spaces"?

Practically speaking, I think it's exceedingly uncommon for someone to think to use tabs, newlines, or more exotic whitespace characters in filenames. I imagine anyone savvy enough to be aware of the existence of whitespace characters other than `' '` will probably also be able to intuit that they shouldn't go in filenames.

**Comment by gcapes** [comment]
@colinmorris Nice neat suggestion and rationale.

**Comment by gdevenyi** [comment]
Sorry, I'm not clear on the suggestion here, are we suggesting changes all mentions of "whitespace" to "spaces"?

**Comment by gcapes** [comment]
Yep. Sacrificing a little bit of detail for simplicity.

**Comment by gcapes** [comment]
@kagross Thanks for bringing this up. This has now been fixed/sidestepped in #915.

**Pull request closed without merging**
