### PR TITLE
added wc explanation

### PR DESCRIPTION
**Pull request by amandamiotto**
Trying to add an easier way of remembering wc by explaining the word count origin

### CODE REVIEW

**Comment by wking** [comment]
On Thu, Feb 12, 2015 at 02:48:11PM -0800, amandamiotto wrote:
> Trying to add an easier way of remembering wc by explaining the word
> count origin

I'm +1 to mentioning this when we introduce wc.  I haven't checked to
see if this is the first time we mention wc, but if it is then I think
this is great.

**Comment by ChristinaLK** [comment]
`wc` is first mentioned in the pipes lesson, but I think this could stand if you add a "remember" or "recall" at the beginning of your parenthetical statement.

**Comment by gvwilson** [comment]
@amandamiotto I'm +1 to merge after @ChristinaLK's suggested wording change.

**Comment by amandamiotto** [comment]
No problems, added the recall bit

**Pull request merged**
