### PR TITLE
Added home directory callout.

### LINKED ISSUE #124: Consider changing /users to /home
Users using modern Linux distributions in their laptops while following the lesson will recognize `/home` immediately, while `/users`  might bring some confusing.

### PR DESCRIPTION
**Pull request by ocefpaf**
Together with #128 this PR closes #124.

### CODE REVIEW

**Comment by ChristinaLK** [comment]
I would actually move the home directory callout to before the alphabet soup one.  

Also, my experience on windows is that home is not My Documents, but something like: 
`c/Users/Name`.  Maybe someone else who has used windows could weigh in...?

**Comment by ocefpaf** [comment]
> Also, my experience on windows is that home is not My Documents

To be honest it is not.  It is something like `C:\Documents and Settings\username`.  However, I am unfamiliar how this directory manifest itself in the various Windows versions (XP, Vista, 7, 8, etc).

I chose `My Documents` because it is present in most of the Windows versions I tried.  Also, I think that the concept of that directory is a similar to the `home` directory.  But I am not a Windows expert!

It is important to notice that a shell class on Windows will use git-bash or cygwin.  I am unsure how those programs handle the `home` directory.  Maybe they create a whole new tree inside the installation directory?  Or maybe do nothing?  I don't know...

**Comment by r-gaia-cs** [comment]
I would suggest to do a big reword of this.

> Next, let's find out where we are by running a command called `pwd` (which stands for "print working directory").
>
> > Alphabet Soup
> >
> > ...
>
> ~~~{.in}
> $ pwd
> ~~~
> ~~~{.out}
> /users/nelle
> ~~~
>
> The computer's response is `/users/nelle`, which is Nelle's home directory.
>
> > Home directory
> >
> > ...
>
> When you open the shell (or any other program) it will be running at your home directory. If you want to run a program in a directory other than your home directory you need to make it explicitly.

**Comment by ocefpaf** [comment]
Looking at your message and the Markdown file I am unsure how to proceed.  Maybe, if the `Home Directory callout` is worth merging, we should merge it as is and re-word in another PR.

**Comment by ChristinaLK** [comment]
I agree @ocefpaf, I think we can merge the callout and then someone can submit the reordering in another PR if they like.  

re: this PR: I would like the callout here to be more specific, something like: "the home directory path will look different on different operating systems. On linux…etc.  "
And for Windows, rather than saying "think of it like My Documents", I would give an actual example of a Windows home directory and then just say that it may look slightly different for different versions of Windows.  
Sorry I wasn't more specific about this before!

**Comment by ocefpaf** [comment]
@ChristinaLK How about now?

**Comment by ChristinaLK** [comment]
that's great, thank you!

**Pull request merged**
