### PR TITLE
Added a tip to use lowercase letters

### PR DESCRIPTION
**Pull request by Serpens**
I added a new tip, as suggested in this issue: https://github.com/swcarpentry/shell-novice/issues/736

### CODE REVIEW

**Review by bkmgit — COMMENTED** [review]
Maybe this could be given as a more general warning.  Typically, it is good to create a separate directory to work in, and keep other existing directories the same.

**Comment by Serpens** [comment]
I can add that, but wouldn’t that be too much? The box is about names, not directory structure.

**Comment by knarrff** [comment]
I don't quite agree. Being consistent with lower/upper case is what is key IMHO. Don't name a file Readme.md and later refer to it as readme.md or README.md, even if your OS allows for that. Other than that I don't think we should tell people to limit their choices here. Not only do most OS environments already create content that does not follow this, even the popular git hosters do, if you let them, pre-populate new repositories with Readme.md or README.md files, and files like LICENSE.md and CONTRIBUTING.md that the Carpentries use themselfes are case-senstitive.

You even get into problems when you think about programming languages that connect internal data structure with file names. A prime example is Java. In Java, file names of files containing classes should match the class name, and at classes should commonly use camel case naming, in particular should start with capital letters. This puts a requirement on capital letters also within file names, at least if you want the code to work on OSs that respect lower/upper case.

**Comment by gcapes** [comment]
My preference is to use lowercase as much as possible, mainly because it makes the typing easier, so I like this tip. However, I don't think it's universal enough that we can suggest it without the caveats in https://github.com/swcarpentry/shell-novice/pull/1323#issuecomment-1354328164, which would then undermine the advice, and make the entry rather too long.

Thanks again for taking the time to contribute.

**Pull request closed without merging**
