### PR TITLE
ENH: Move challenges into episode (Issue #637)

### PR DESCRIPTION
**Pull request by yeemey**
Hi everyone, I'm working on a few of these for #637. Thanks!

- [x] shell-novice/_episodes/02-filedir.md
- [x] shell-novice/_episodes/03-create.md
- [x] shell-novice/_episodes/04-pipefilter.md

### CODE REVIEW

**Comment by yeemey** [comment]
Episode 03 appears to be short enough that having the challenges appear at the end seems ok. Let me know if I should move them anyway - thanks!

**Comment by shwina** [comment]
@gdevenyi @gcapes (and anyone else!)

What do you think about this departure from the lesson layout? I'm strongly in favour.

**Comment by gcapes** [comment]
Yep, it looks like a good idea to me!

**Comment by shwina** [comment]
Thank you, @yeemey!

**Pull request merged**
