### PR TITLE
Gh pages

### PR DESCRIPTION
**Pull request by maglet**
Removed html, changed formatting for answer #s so they no longer appear as headings.

### CODE REVIEW

**Comment by gvwilson** [comment]
1. Please re-submit with the HTML files removed.
2. Do we want to recommend deleting lots of files this way? I suspect someone will wind up deleting the 'good' copy.

**Comment by gvwilson** [comment]
Hi @maglet - please re-submit as requested.

**Comment by maglet** [comment]
Sorry Greg, I changed institutions and hadn't changed my email on my git account, so I wasn't getting these notifications. I'll get on this ASAP

**Comment by gdevenyi** [comment]
Closed in favour of #446

**Pull request closed without merging**
