### PR TITLE
removing backup dirs, renaming filesystem to data

### PR DESCRIPTION
**Pull request by ChristinaLK**
See also #62.  This at least cleans up the directory.

### CODE REVIEW

**Comment by wking** [comment]
On Thu, Feb 12, 2015 at 06:14:55PM -0800, Christina Koch wrote:
> * removing backup dirs, renaming filesystem to data, moving nelle up
>   one directory level

This looks pretty good to me, but I have a few questions…

>     R data/nelle/Desktop/.my.log (0)

Moved from filesystem/users/nelle/writing/old/.  It doesn't look like
we ever reference this file, so I'd just remove it.

>     R data/nelle/creatures/basilisk.dat (0)
>     R data/nelle/creatures/unicorn.dat (0)

I'd rather remove these and stick to the small pdb directory, but that
can wait until a follow-up PR, since we currently reference these from
04-loop.md, and 05-script.md.

>     R data/nelle/data/elements/Ac.xml (0)
>     R data/nelle/data/elements/Ag.xml (0)

The ‘elements’ directory shows up in two 01-filedir.md listings, but
we never actually look inside.  I'd remove it and update the listings,
but that can wait until a follow-up PR.

>     R data/nelle/data/morse.txt (0)

This also only shows up in the 01-filedir.md listings.  I'd remove it
and update the listings, but that can wait until a follow-up PR.

>     R data/nelle/data/pdb/aldrin.pdb (0)
>     R data/nelle/data/pdb/ammonia.pdb (0)

I don't think we ever look inside this directory (just the alternative
directory with fewer PDB files).  I'd remove it and update any
listings that show the ‘pdb’ directory, but that can wait until a
follow-up PR.

>     R data/nelle/data/planets.txt (460)
>     R data/nelle/data/sunspot.txt (0)

These also only show up in the 01-filedir.md listings.  I'd remove it
and update the listings, but that can wait until a follow-up PR.

>     R data/nelle/molecules/cubane.pdb (0)
>     R data/nelle/molecules/ethane.pdb (0)
>     R data/nelle/molecules/methane.pdb (0)
>     R data/nelle/molecules/octane.pdb (0)
>     R data/nelle/molecules/pentane.pdb (0)
>     R data/nelle/molecules/propane.pdb (0)

These are the only PDB files I think we want to keep.

>     R data/nelle/north-pacific-gyre/2012-07-03/NENE01729A.txt (0)
>     R data/nelle/north-pacific-gyre/2012-07-03/NENE01729B.txt (0)

This directory is useful for pattern matching and the like, and for
showing an example where the shell speedups are useful.  I think we
need to keep it.

>     R data/nelle/notes.txt (0)
>     R data/nelle/pizza.cfg (0)
>     R data/nelle/solar.pdf (0)

I think these are mostly filler to make the home directory look lived
in.  That's fine, but I don't think we need the binary solar.pdf.

>     R data/nelle/writing/data/one.txt (140)
>     R data/nelle/writing/data/two.txt (600)
>     R data/nelle/writing/haiku.txt (0)
>     R data/nelle/writing/old/.my.log (0)

I dont' think we ever show these.  I'd remove them.

>     R data/nelle/writing/thesis/empty-draft.md (0)
>     R data/nelle/writing/tools/format (0)
>     R data/nelle/writing/tools/old/oldtool (0)
>     R data/nelle/writing/tools/stats (0)

I don't think we ever use these.  I'd remove them.

**Comment by lexnederbragt** [comment]
I think the folder is called 'filesystem' because it is meant to illustrate nelle's filesystem, with the teaching starting from her home directory. Renaming it to 'data' is perhaps confusing, also because there is a 'data' folder in 'nelle'.

**Comment by ChristinaLK** [comment]
My thinking was to shorten the path from top level -> actual files used in the lesson, with `data` as the top-level directory to match lesson-template conventions.  I could change the top-level `data` to `filesystem` though if that would be clearer in this instance.

**Comment by ChristinaLK** [comment]
To be revisited...

**Pull request merged**
