### PR TITLE
Update due changes on lessons template

### PR DESCRIPTION
**Pull request by r-gaia-cs**
**This include a merge from `core` branch of https://github.com/swcarpentry/lesson-template/.**

## Commits to review

- [ ] 9808e9c
- [ ] d9e4899

### CODE REVIEW

**Comment by wking** [comment]
On Thu, Feb 05, 2015 at 05:51:46AM -0800, Raniere Silva wrote:
> ## Commits to review
> 
> - [ ] 9808e9c
> - [ ] d9e4899

Why single these out for review?  9808e9c looks pretty
straightforward, and d9e4899 is auto-generated (and therefore to
complicated to be worth reviewing, in my opinion).

**Comment by r-gaia-cs** [comment]
> Why single these out for review?

I don't want to scare people with all this changes that this pull request will add.

**Comment by wking** [comment]
On Thu, Feb 05, 2015 at 05:12:39PM -0800, Raniere Silva wrote:
> > Why single these out for review?
> 
> I don't want to scare people with all this changes that this pull
> request will add.

I think the best approach here is to just trust the template
maintainers, explain any non-trivial conflicts and their resolution,
and give a high-level overview of the changes.  In this case:

  $ git log --graph --topo-order --oneline --decorate origin/pr/64
  * d9e4899 (origin/pr/64) Update HTML pages due lesson template changes
  * 9808e9c Add class objectives
  *   e20bcad Merge branch 'core' into shell-template-update
  |\
  | *   e6b9507 Merge pull request #146 from abought/104_callouts
  … …
  $ git merge-base e20bcad^ e20bcad^2
  1fdc82b1f98f973c94e0aef2fc02a2667cec0a3b
  $ git log --first-parent --oneline 1fdc82b..e20bcad^2
  e6b9507 Merge pull request #146 from abought/104_callouts
  0ba3dc3 Merge pull request #147 from jdblischak/fig.path
  dfe4de7 Merge remote-tracking branch 'swc/core' into core
  89df963 Use unified CSS from site.
  3178d12 Merge pull request #136 from gvwilson/core

so if folks accept those high-level changes and your follow-up tweaks
in 9808e9c, I don't think there's any need to review the
auto-generated d9e4899 or the details of the template-side commits.

**Comment by ChristinaLK** [comment]
This is mostly formatting stuff, correct?  Adding appropriate syntax to the .md files, regenerating .html, and changing the "FIXME" titles of exercises?  If there's anything else I should look at, specifically, let me know.

**Comment by wking** [comment]
On Thu, Feb 05, 2015 at 07:02:45PM -0800, Christina Koch wrote:
> … changing the "FIXME" titles of exercises?

That particlar part is just a side-effect of rebuilding the HTML after
the recently-merged edits from #30, #32, #34, and #35.  In my earlier
summary of the template pulls that this brings in [1], the backwards
merge in dfe4de7 (Merge remote-tracking branch 'swc/core' into core,
2015-01-27) means my --first-parent line missed a few:

  $ git log --first-parent --oneline 1fdc82b..dfe4de7^2
  5aaa891 Merge pull request #135 from r-gaia-cs/core-improve-setup-labels
  7a3143a Merge pull request #131 from r-gaia-cs/core-check-required-files
  3178d12 Merge pull request #136 from gvwilson/core

Where 3178d12 showed up in the earlier listing.  A more robust listing
in the face of backwards merges might be:

  $ git log --oneline 1fdc82b..e20bcad^2 | grep 'Merge pull request'
	e6b9507 Merge pull request #146 from abought/104_callouts
	0ba3dc3 Merge pull request #147 from jdblischak/fig.path
	5aaa891 Merge pull request #135 from r-gaia-cs/core-improve-setup-labels
	7a3143a Merge pull request #131 from r-gaia-cs/core-check-required-files
	3178d12 Merge pull request #136 from gvwilson/core

which shows all the template features that this PR is bringing in:

* swcarpentry/lesson-template#146 (Add validation for callout boxes)
* swcarpentry/lesson-template#147 (Set fig.path in tools/chunk-options.R…)
* swcarpentry/lesson-template#135 (Improve script to setup labels)
* swcarpentry/lesson-template#131 (Validator should check for required files)
* swcarpentry/lesson-template#136 (Import style for slides…)

Kudos for @r-gaia-cs for the feature branch names that largely match
the pull-request summaries ;).

[1]: https://github.com/swcarpentry/shell-novice/pull/64#issuecomment-73175380

**Comment by ChristinaLK** [comment]
@r-gaia-cs , @wking , if I merge this now, is it likely that the most recent round of small PRs will need to be updated b/c of conflicts?

**Comment by r-gaia-cs** [comment]
> if I merge this now

I need to rebase this pull request.

> is it likely that the most recent round of small PRs will need to be updated b/c of conflicts?

Yes. @ChristinaLK what do you think to us merge as much as possible pull request during the the weekend and merge this at the end of the weekend?

**Comment by ChristinaLK** [comment]
I'm w/o a computer from Friday afternoon until Monday.  :P  
Of the recent PR's, #63 #67 and #69 are pretty much ready to go, I could merge them tonight.  Almost everything else needs a bit of discussion, so probably wouldn't be ready until later anyway.  How about I merge those three I listed, you rebase and merge this, and then we go from there?

**Comment by r-gaia-cs** [comment]
> How about I merge those three I listed, you rebase and merge this, and then we go from there? 

@ChristinaLK I assigned #63 #67 and #69 to you. I will wait you merge this three pull request and give me a call to rebase and merge this.

**Comment by wking** [comment]
On Thu, Feb 12, 2015 at 06:23:31PM -0800, Raniere Silva wrote:
> > is it likely that the most recent round of small PRs will need to
> > be updated b/c of conflicts?
> 
> Yes.

Really?  The changes here don't touch the *content* of the lessons
much.  I'd expect that this PR will commute with pure-content PRs like
the ones we've been getting from Melbourne (except for PRs that touch
the HTML, which they shouldn't be doing [1]).

Personally, I'd prioritize merging *anything* that is merge-able,
since 17 in-flight PRs is more than *I* can keep track of in my head
at once ;).  If some folks end up with conflicts, you can either
resolve those yourself when merging/rebasing from the command line or
ask the original contributor to rebase their branch (depending on
their interest in learning to rebase).  I'd also try to clear the deck
before the next round of instructor training launches the its PR salvo
;).

[1]: https://github.com/swcarpentry/lesson-template/blob/core/CONTRIBUTING.md#getting-started

**Comment by ChristinaLK** [comment]
Okay, everything that's ready to merge (w/o awaiting further discussion) has been merged, could maybe squeak in #72 (I won't be able to merge, but any other maintainer could)?  Otherwise, go ahead and rebase/merge this in, so our html finally matches our md.

**Comment by r-gaia-cs** [comment]
@ChristinaLK I'm closing this since I merge `core` at a3dde10 and update the HTML pages at 324df41.

**Comment by wking** [comment]
On Fri, Feb 13, 2015 at 12:04:15PM -0800, Raniere Silva wrote:
> @ChristinaLK I'm closing this since I merge `core` at a3dde10 and
> update the HTML pages at 324df41.

Hmm, I don't think we need both:

> 5.  The maintainers for this repository are [Christina
>     Koch][christina] and [Gabriel Devenyi][gabriel].  Feel free to
>     contact them if you have any questions or languishing pull
>     requests.

and:

> 3.  The [list of maintainers][swc-maintainers] on the [Software
>     Carpentry website][swc-website] lists the people currently
>     responsible for managing this repository.

Personally, I prefer the local listing, since I don't see a benefit to
collecting the list of maintainers in a central location and think the
maintainer information should be versioned in the repository itself.
That makes it easy to answer questions like "who was maintaining this
lesson when PR 123 landed?".

Also:

> [issues]: https://github.com/swcarpentry/lesson-template/issues

needs to be updated to point at this repository's issues.

**Pull request closed without merging**
